apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          # GitHub Actions updates this line after pushing to ECR.
          image: 590183737254.dkr.ecr.ap-southeast-1.amazonaws.com/day3-backend:0ba83173066be84fb3466de565a6f2cf74184696
          env:
            - name: OTEL_SERVICE_NAME
              value: backend
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: lgtm.observability.svc.cluster.local:4317
            - name: SERVICE_VERSION
              value: 0ba83173066be84fb3466de565a6f2cf74184696
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              cpu: 50m
              memory: 96Mi
            limits:
              cpu: 300m
              memory: 384Mi
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: application
spec:
  selector:
    app: backend
  ports:
    - name: http
      port: 8080
      targetPort: http
