apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-otel
  namespace: application
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backend-otel-metadata
  namespace: application
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["replicasets", "deployments"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backend-otel-metadata
  namespace: application
subjects:
  - kind: ServiceAccount
    name: backend-otel
    namespace: application
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: backend-otel-metadata
