apiVersion: v1
kind: ServiceAccount
metadata:
  name: loki
  namespace: observability
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tempo
  namespace: observability
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mimir
  namespace: observability
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pyroscope
  namespace: observability
